version: "3.9"

services:
  x-nginx:
    image: nginx:latest
    container_name: medhanite-medical-center-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    depends_on:
      - x-db
    networks:
      - medhanite-medical-center-network

  x-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medhanite-medical-center
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    networks:
      - medhanite-medical-center-network

  x-db:
    image: mysql:8.0
    container_name: medhanite-medical-center-db
    restart: unless-stopped
    environment:
         # commented because we are NOT using empty or black password in mysql
      # MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ${DB_DATABASE}
         # UNCommented because we are NOT using root user of mysql
      MYSQL_USER: ${DB_USERNAME}
      # MYSQL_USER_HOST: localhost # NO Such thing
         # UNCommented because we are NOT using root user of mysql
      MYSQL_PASSWORD: ${DB_PASSWORD}
         # UNCommented because we are using root user of mysql and the root user password it could be either blank empty password or normal password
         # comment this if you do NOT want additional second root user ('root'@'%') with any where access to be create // by defalut there will always be root user with localhost in mysql
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
         # to create the root user make its host localhost NOT remote or Anywhere
         # root is localhost because we have new mysql user for our laravel we will use the new user and root will be localhost because it have all privilages so it is dangerous to give root remote access 
      MYSQL_ROOT_HOST: localhost
      # MYSQL_HOST: localhost # this may create complications # NOT tryed
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - medhanite-medical-center-network

volumes:
  db_data:

networks:
  medhanite-medical-center-network:
    driver: bridge
